name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install xterm network-manager
    - name: Change user to root
    - name: Check workflows
      run: echo "$EUID"
    - name: Check dependencies
      run: ./configure
    - name: install
      run: ./install.sh
    - name: uninstall
      run: ./install.sh remove
